version: "3"

services:
  app:
    restart: always
    container_name: app-server
    hostname: app-server
    build: ./app
    volumes:
      - "./app:/var/www/"
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
  web:
    container_name: web-server
    hostname: web-server
    build: ./web
    volumes:
      - "./web/nginx.conf:/etc/nginx/nginx.conf"
      - "/tmp/nginx_log:/var/log/nginx"
    ports:
      - "8000:80"
    environment:
      TZ: Asia/Tokyo